'use client'
import { useMemo,useState } from 'react'
import { useRouter } from 'next/navigation'
import { Check,LoaderCircle,Pencil,ShieldOff,ShieldCheck,UserPlus } from 'lucide-react'
import type { GovernmentUserRow,ProvisionArea } from '@/modules/admin/government-users'
import type { GovernmentMembershipRole } from '@/modules/admin/policy'
import { Alert,EmptyState,SectionHeader,Surface } from './ui/civic'
import { PasswordInput } from './password-input'

type Result={error?:string;message?:string}
export function AdminGovernmentUsers({areas,rows}:{areas:ProvisionArea[];rows:GovernmentUserRow[]}){
 const router=useRouter(),regions=useMemo(()=>Array.from(new Map(areas.map(area=>[area.regionId,area.regionName])).entries()).map(([id,name])=>({id,name})),[areas])
 const [mode,setMode]=useState<'invite'|'password'>('invite'),[region,setRegion]=useState(regions[0]?.id||''),[busy,setBusy]=useState(''),[result,setResult]=useState<Result>({}),[editing,setEditing]=useState('')
 async function request(name:string,method:'POST'|'PATCH',body:unknown){
  setBusy(name);setResult({})
  try{const response=await fetch('/api/admin/government-users',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),payload=await response.json();if(!response.ok)throw new Error(payload.error||'The account operation failed.');setResult({message:payload.message});setEditing('');router.refresh();return true}
  catch(error){setResult({error:error instanceof Error?error.message:'The account operation failed.'});return false}finally{setBusy('')}
 }
 const grouped=regions.map(item=>({...item,areas:areas.filter(area=>area.regionId===item.id)}))
 return <div className="admin-users-layout"><Surface><SectionHeader title="Create Government Account"><UserPlus size={21}/></SectionHeader><form className="admin-provision-form" onSubmit={async event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),ok=await request('create','POST',{name:data.get('name'),email:data.get('email'),mode,password:mode==='password'?data.get('password'):undefined,jurisdictionId:data.get('jurisdictionId'),role:data.get('role')});if(ok){form.reset();setMode('invite');setRegion(regions[0]?.id||'')}}}>
  <div className="admin-form-grid"><label>Full name<input name="name" autoComplete="name" minLength={2} maxLength={80} required/></label><label>Email<input name="email" type="email" autoComplete="email" required/></label><label>Account setup<select value={mode} onChange={event=>setMode(event.target.value as 'invite'|'password')}><option value="invite">Send secure invite</option><option value="password">Set initial password</option></select></label>{mode==='password'?<label>Initial password<PasswordInput name="password" autoComplete="new-password" minLength={12} maxLength={128} required/><span className="caption">12+ characters with uppercase, lowercase, number, and symbol.</span></label>:<div className="admin-invite-note"><ShieldCheck size={18}/><p>Supabase emails a one-time invite. The user chooses their password.</p></div>}<label>Province / Region<select value={region} onChange={event=>setRegion(event.target.value)} required>{regions.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>City / Civic Area<select name="jurisdictionId" required defaultValue="" key={region}><option value="">Choose civic area</option>{areas.filter(area=>area.regionId===region).map(area=><option key={area.id} value={area.id}>{area.name}</option>)}</select></label><label>Government role<select name="role" defaultValue="reviewer"><option value="reviewer">Reviewer</option><option value="operator">Operator</option></select></label></div>
  {!areas.length&&<Alert tone="warning">Add at least one local civic area before creating Government accounts.</Alert>}<button className="primary-button admin-submit" disabled={!!busy||!areas.length}>{busy==='create'?<LoaderCircle className="spin" size={17}/>:<UserPlus size={17}/>} Create Government Account</button>
 </form>{result.error&&<Alert tone="error">{result.error}</Alert>}{result.message&&<Alert tone="success">{result.message}</Alert>}</Surface>
 <Surface><SectionHeader title="Existing Government users"><span className="muted">{rows.length} membership{rows.length===1?'':'s'}</span></SectionHeader>{!rows.length?<EmptyState title="No Government users yet" description="New accounts and their assigned areas will appear here."/>:<div className="admin-table-wrap"><table className="admin-users-table"><thead><tr><th>Name</th><th>Email</th><th>Jurisdiction</th><th>Role</th><th>Status</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{rows.map(row=>{
  const isEditing=editing===row.membershipId,status=!row.active?'Disabled':row.invited?'Invited':'Active'
  return <tr key={row.membershipId}><td><strong>{row.name}</strong></td><td>{row.email}</td><td>{isEditing?<select aria-label="Jurisdiction" defaultValue={row.jurisdictionId} id={`area-${row.membershipId}`}>{grouped.map(group=><optgroup key={group.id} label={group.name}>{group.areas.map(area=><option value={area.id} key={area.id}>{area.name}</option>)}</optgroup>)}</select>:row.jurisdiction}</td><td>{isEditing?<select aria-label="Government role" defaultValue={row.role} id={`role-${row.membershipId}`}><option value="reviewer">Reviewer</option><option value="operator">Operator</option></select>:roleLabel(row.role)}</td><td><span className={`access-status access-${status.toLowerCase()}`}>{status}</span></td><td><div className="table-actions">{isEditing?<><button className="table-action" disabled={!!busy} onClick={()=>{const area=(document.getElementById(`area-${row.membershipId}`) as HTMLSelectElement).value,role=(document.getElementById(`role-${row.membershipId}`) as HTMLSelectElement).value as GovernmentMembershipRole;void request(`edit-${row.membershipId}`,'PATCH',{action:'edit',membershipId:row.membershipId,jurisdictionId:area,role})}}>{busy===`edit-${row.membershipId}`?<LoaderCircle className="spin" size={15}/>:<Check size={15}/>} Save</button><button className="table-action" disabled={!!busy} onClick={()=>setEditing('')}>Cancel</button></>:<button className="table-action" disabled={!!busy} onClick={()=>setEditing(row.membershipId)}><Pencil size={15}/> Edit membership</button>}<button className={`table-action ${row.active?'disable-action':''}`} disabled={!!busy} onClick={()=>{if(row.active&&!window.confirm(`Disable all Government Portal access for ${row.name}?`))return;void request(`access-${row.userId}`,'PATCH',{action:'access',userId:row.userId,enabled:!row.active})}}>{busy===`access-${row.userId}`?<LoaderCircle className="spin" size={15}/>:row.active?<ShieldOff size={15}/>:<ShieldCheck size={15}/>} {row.active?'Disable access':'Enable access'}</button></div></td></tr>
 })}</tbody></table></div>}</Surface></div>
}
function roleLabel(role:GovernmentMembershipRole){return role==='operator'?'Operator':'Reviewer'}
