'use client'
import dynamic from 'next/dynamic'
import { useMemo,useState } from 'react'
import type { PublicIncident } from '@/modules/incidents/queries'
import type { Area } from './jurisdiction-form'
import { IncidentList } from './incident-list'
const IncidentMap=dynamic(()=>import('./incident-map'),{ssr:false,loading:()=> <p role="status">Loading map…</p>})
export function ExploreView({incidents,areas}:{incidents:PublicIncident[];areas:Area[]}) {
 const [region,setRegion]=useState(''),[city,setCity]=useState(''),[status,setStatus]=useState(''),[urgency,setUrgency]=useState(''),[category,setCategory]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('')
 const filtered=useMemo(()=>incidents.filter(i=>(!city||i.jurisdiction_id===city)&&(!region||areas.some(a=>a.id===i.jurisdiction_id&&a.parent_id===region))&&(!status||i.status===status)&&(!urgency||i.urgency===urgency)&&(!category||i.category===category)&&(!from||i.created_at.slice(0,10)>=from)&&(!to||i.created_at.slice(0,10)<=to)),[incidents,areas,region,city,status,urgency,category,from,to])
 return <><div className="filter-bar"><label>Province / Region<select value={region} onChange={e=>{setRegion(e.target.value);setCity('')}}><option value="">Pakistan · all regions</option>{areas.filter(a=>a.level_label==='province'||a.level_label==='region').map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label><label>Civic area<select value={city} onChange={e=>setCity(e.target.value)}><option value="">All civic areas</option>{areas.filter(a=>a.level_label==='local'&&(!region||a.parent_id===region)).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['ACCEPTED','IN_PROGRESS','RESOLVED','VERIFIED_RESOLVED','FLAGGED_FOR_REREVIEW'].map(s=><option key={s} value={s}>{s.replaceAll('_',' ').toLowerCase()}</option>)}</select></label><label>Urgency<select value={urgency} onChange={e=>setUrgency(e.target.value)}><option value="">Both urgency lanes</option><option value="URGENT_HAZARD">Urgent Civic Hazard</option><option value="MAINTENANCE">Civic Maintenance</option></select></label></div><details className="extra-filters"><summary>Category and dates</summary><div className="filter-bar"><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{Array.from(new Set(incidents.map(i=>i.category).filter((c):c is string=>!!c))).map(c=><option key={c}>{c}</option>)}</select></label><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} min={from} onChange={e=>setTo(e.target.value)}/></label></div></details><IncidentMap incidents={filtered}/><div className="section-heading"><h2>Public incidents</h2><span className="muted">{filtered.length} shown</span></div><IncidentList items={filtered.map(i=>({id:i.id,title:i.category||'Civic issue',date:i.created_at,status:i.status,urgency:i.urgency,area:areas.find(a=>a.id===i.jurisdiction_id)?.name}))} empty="No public incidents match this view."/></>
}
