'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { Check,LoaderCircle,Upload,TriangleAlert } from 'lucide-react'
import { addGovernmentUpdate,resolveIncident,reviewIncident } from '@/modules/government/actions'
import { GOVERNMENT_CATEGORIES,GOVERNMENT_WORKSTREAMS } from '@/modules/government/policy'
import { Alert } from './ui/civic'

type Result={error?:string;message?:string}
export function GovernmentActions({incidentId,status,urgency,canReview,canOperate}:{incidentId:string;status:string;urgency:string|null;canReview:boolean;canOperate:boolean}){
 const router=useRouter(),[busy,setBusy]=useState(''),[result,setResult]=useState<Result>({}),[files,setFiles]=useState<{id:string;file:File}[]>([])
 async function run(name:string,action:()=>Promise<Result>){setBusy(name);setResult({});try{const next=await action();setResult(next);if(next.message)router.refresh()}catch(error){setResult({error:error instanceof Error?error.message:'The action could not be completed. Please retry.'})}finally{setBusy('')}}
 if(['SUBMITTED','ACCEPTED','IN_PROGRESS'].includes(status)&&!canReview)return <Alert>This account can view this report, but actions are limited to your assigned civic area.</Alert>
 if(status==='SUBMITTED')return <div className="government-action-stack"><section className="action-panel"><h3>Accept and assign</h3><p>Confirm the classification and responsible workstream.</p><form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void run('accept',()=>reviewIncident({incidentId,action:'ACCEPT',category:form.get('category'),urgency:form.get('urgency'),workstream:form.get('workstream')}))}}><label>Category<select name="category" required defaultValue=""><option value="">Choose category</option>{GOVERNMENT_CATEGORIES.map(value=><option key={value}>{value}</option>)}</select></label><label>Urgency<select name="urgency" required defaultValue={urgency||''}><option value="">Choose urgency</option><option value="URGENT_HAZARD">Urgent Civic Hazard · 48 hours</option><option value="MAINTENANCE">Civic Maintenance · 7 days</option></select></label><label>Workstream<select name="workstream" required defaultValue=""><option value="">Choose workstream</option>{GOVERNMENT_WORKSTREAMS.map(value=><option key={value}>{value}</option>)}</select></label><button className="primary-button" disabled={!!busy}>{busy==='accept'?<LoaderCircle className="spin" size={17}/>:<Check size={17}/>} Accept report</button></form></section><section className="action-panel danger-panel"><h3>Reject with reason</h3><p>The citizen will see this reason. It becomes part of the audit history.</p><form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void run('reject',()=>reviewIncident({incidentId,action:'REJECT',reason:form.get('reason')}))}}><label>Reason<textarea name="reason" minLength={20} maxLength={500} rows={4} required placeholder="Explain clearly why this report cannot be accepted."/></label><button className="secondary-button danger-button" disabled={!!busy}>{busy==='reject'?<LoaderCircle className="spin" size={17}/>:<TriangleAlert size={17}/>} Reject report</button></form></section>{result.error&&<Alert tone="error">{result.error}</Alert>}{result.message&&<Alert tone="success">{result.message}</Alert>}</div>
 if(['ACCEPTED','IN_PROGRESS'].includes(status)&&!canOperate)return <Alert>Operator access is required to publish progress and completion evidence. Reviewers can accept or reject submitted reports.</Alert>
 if(['ACCEPTED','IN_PROGRESS'].includes(status))return <div className="government-action-stack"><section className="action-panel"><h3>Post progress</h3><form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void run('update',()=>addGovernmentUpdate({incidentId,body:form.get('body')}))}}><label>Public update<textarea name="body" minLength={10} maxLength={500} rows={3} required placeholder="What action has the civic team taken?"/></label><button className="secondary-button" disabled={!!busy}>Publish update</button></form></section><section className="action-panel resolve-panel"><h3>Resolve with proof</h3><p>Add 1–5 completion photos and a clear public note.</p><form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void run('resolve',async()=>{if(!files.length)return {error:'Choose at least one completion photo.'};for(const item of files){const upload=new FormData();upload.set('incidentId',incidentId);upload.set('uploadId',item.id);upload.set('photo',item.file);const response=await fetch('/api/government/evidence',{method:'POST',body:upload}),payload=await response.json();if(!response.ok)throw new Error(payload.error||'Photo upload failed.')}return resolveIncident({incidentId,notes:form.get('notes'),uploadIds:files.map(item=>item.id)})})}}><label>Completion photos<input type="file" accept="image/jpeg,image/png" multiple required onChange={event=>{const selected=Array.from(event.target.files||[]).slice(0,5);setFiles(selected.map(file=>({id:crypto.randomUUID(),file})))}}/><span className="caption">{files.length?`${files.length} selected`:'JPEG or PNG · up to 5 MB each'}</span></label><label>Resolution note<textarea name="notes" minLength={20} maxLength={500} rows={4} required placeholder="Describe the completed work and what the photos show."/></label><button className="primary-button" disabled={!!busy||!files.length}>{busy==='resolve'?<><LoaderCircle className="spin" size={17}/> Uploading and resolving…</>:<><Upload size={17}/> Publish resolution</>}</button></form></section>{result.error&&<Alert tone="error">{result.error}</Alert>}{result.message&&<Alert tone="success">{result.message}</Alert>}</div>
 const resolved=['RESOLVED','VERIFIED_RESOLVED'].includes(status)
 return <Alert tone={resolved?'success':'info'}>{resolved?'This incident is resolved. Its completion evidence and history are public.':'This report has already been reviewed.'}</Alert>
}
